<?php

return array(
    array("name"=>"ADEME", "logo"=>"LOGO ADEME.png"),
    array("name"=>"ADERA", "logo"=>"logo-adera.png"),
    array("name"=>"Agence de l’Eau Adour Garonne", "logo"=>"Logo-Agence-de-l-eau-Adour-Garonne.png"),
    array("name"=>"Agence de l’Eau Seine-Normandie", "logo"=>"Logo-eau-seine-normandie.png"),
    array("name"=>"Agence Universitaire de la Francophonie", "logo"=>"Logo-AUF.png"),
    array("name"=>"Ambassade de France Australie", "logo"=>"logo-ambassade-france-australie.png"),
    array("name"=>"ANR", "logo"=>"New-logo-ANR-PNG.png"),
    array("name"=>"ANRT", "logo"=>"logo-anrt.png"),
    array("name"=>"ANSES", "logo"=>"logo-ANSES.png"),
    array("name"=>"ARBNA", "logo"=>"LOGO ARBNA.png"),
    array("name"=>"ARS", "logo"=>"logo-ARS.jpg"),
    array("name"=>"AWI", "logo"=>"logo-AWI.png"),
    array("name"=>"BNP Paribas", "logo"=>"LOGO BNP PARIBAS.png"),
    array("name"=>"Bordeaux INP", "logo"=>"bordeaux_inp_couleur_rvb.jpg"),
    array("name"=>"Bordeaux Métropole", "logo"=>"bordeaux-metropole.png"),
    array("name"=>"BRGM", "logo"=>"BRGM-logo.png"),
    array("name"=>"Carnot ISIFOR", "logo"=>"institut-carnot-isifor.png"),
    array("name"=>"Cdc Médoc Atalantique", "logo"=>"logo_medoc_atlantique.png"),
    array("name"=>"Cedre", "logo"=>"logo-cedre-hd.png"),
    array("name"=>"CNRS", "logo"=>"LOGO_CNRS_BLEU.png"),
    array("name"=>"Conseil Départemental de Gironde", "logo"=>"logo-département-gironde.png"),
    array("name"=>"consortium MAGEST", "logo"=>"logo-magest.png"),
    array("name"=>"CPIER Vallée de Seine", "logo"=>"logo_vds.png"),
    array("name"=>"CRC", "logo"=>"logo-CRC.png"),
    array("name"=>"CRNA", "logo"=>null),
    array("name"=>"CSIC", "logo"=>"logo-CSIC.png"),
    array("name"=>"Dordogne Biosphere", "logo"=>"tetier biosphere 2020(1).png"),
    array("name"=>"Dordogne DIREN", "logo"=>"logo-direndordogne.png"),
    array("name"=>"DREAL AQUITAINE", "logo"=>"DREAL-logo.png"),
    array("name"=>"EDF", "logo"=>"EDF.png"),
    array("name"=>"EPTB Rance Frémur Baie de Beaussais", "logo"=>"EPTB-logo.png"),
    array("name"=>"Europe", "logo"=>"logo-UE.png"),
    array("name"=>"FEADER", "logo"=>"FEADER-LOGO.png"),
    array("name"=>"Fondation de Bordeaux", "logo"=>"FONDATION_BDX_logo.png"),
    array("name"=>"fondation Euskampus", "logo"=>"fondation Euskampus-logo.png"),
    array("name"=>"Ford", "logo"=>"Ford logo.png"),
    array("name"=>"France Berkeley Funds", "logo"=>"logo-ucberkeley-white.png"),
    array("name"=>"GIP Seine-Aval", "logo"=>"LOGO-GIP Seine-Aval.png"),
    array("name"=>"GIS Sol", "logo"=>"logo-GIS.png"),
    array("name"=>"Gobilab", "logo"=>"logo-gobilab.png"),
    array("name"=>"Grand Port Maritime de Bordeaux", "logo"=>"logo-bordeauxport.png"),
    array("name"=>"IFREMER", "logo"=>"Logo Ifremer Blanc.png"),
    array("name"=>"INTERREG-AA", "logo"=>"INTERREG-AA-logo.png"),
    array("name"=>"IODP France", "logo"=>"cropped-cropped-IODP-France-2.png"),
    array("name"=>"IReSP", "logo"=>"IResp-logo.png"),
    array("name"=>"JPI Oceans", "logo"=>"JPI Oceans-logo.png"),
    array("name"=>"MESR", "logo"=>"MESR-logo.png"),
    array("name"=>"Monash University", "logo"=>"Monash University-logo.png"),
    array("name"=>"Nexans", "logo"=>"Nexans-logo.png"),
    array("name"=>"NRF South Korea", "logo"=>"NRF South Korea - logo.png"),
    array("name"=>"OASU", "logo"=>"OASULOGO.jpg"),
    array("name"=>"OFB", "logo"=>"OFB-logo.png"),
    array("name"=>"ONF Landes Nord Aquitaine", "logo"=>"ONF Landes Nord Aquitaine logo.png"),
    array("name"=>"Parc Naturel Marin du Bassin d’Arcachon", "logo"=>"Parc Naturel Marin du Bassin d’Arcachon logo.png"),
    array("name"=>"Campus France", "logo"=>"logo-campus-france.png"),
    array("name"=>"PNR Causses du Quercy", "logo"=>"logo-footer.png"),
    array("name"=>"PNRA", "logo"=>"logo-header-PNRA.png"),
    array("name"=>"Préfecture de Guyane", "logo"=>"prefecture-guyane-logo.png"),
    array("name"=>"PSL Global Seed Fund", "logo"=>"LOGO-PSL.png"),
    array("name"=>"Qualyse", "logo"=>"Qualyse-logo.png"),
    array("name"=>"REGION", "logo"=>"logo_na_horiz_BLANC_2019.png"),
    array("name"=>"Renault", "logo"=>"Renault logo.png"),
    array("name"=>"Rutherford Discovery Fellowship (NZ)", "logo"=>"RS-sub-brand-Rutherford-Foundation-landscape-with-bleed-RGB.jpg"),
    array("name"=>"SCAR", "logo"=>"scar-logo.png"),
    array("name"=>"SIBA", "logo"=>"siba-logo.png"),
    array("name"=>"SMEAG", "logo"=>"logo-SMEAG.png"),
    array("name"=>"Sogeti", "logo"=>"sogeti-logo.png"),
    array("name"=>"Stanford University (US)", "logo"=>"Stanford University - logo.png"),
    array("name"=>"Syndicat Mixte du Bassin Versant des Lacs du Born (SMBVLB)", "logo"=>"SAGE-Born-et-Buch.png"),
    array("name"=>"Total", "logo"=>"Total logo.jpg"),
    array("name"=>"UKRI", "logo"=>"urkri-logo.png"),
    array("name"=>"Université Bordeaux", "logo"=>"logo_ubx.gif"),
    array("name"=>"Université du Pays Basque", "logo"=>"Université du Pays Basque - logo.png"),
    array("name"=>"Veolia", "logo"=>"veolia logo.png")
);
